# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy rest of source code
COPY . .

# Build the project
RUN npm run build

# Expose any necessary port (if needed)
# ENV PORT=3000

# Define default command
CMD ["node", "build/index.js"]
